{% set name = "chainconsumer" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/chainconsumer-{{ version }}.tar.gz
  sha256: 2d882524309180e7bb352e382b518de0b8bdc4d43b05a814a1c56861744b2a8f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python 3.11.13
    - poetry-core
    - pip
  run:
    - python 3.11.13
    - numpy >=1.23.0
    - scipy >=1.8.0
    - matplotlib-base >=3.6.0,<4.0.0
    - statsmodels >=0.14.0,<1
    - pandas >=2.1.1,<3.0.0
    - pillow >=10.0.1
    - pydantic 2.11.7

test:
  imports:
    - chainconsumer
  commands:
    - pip check
  requires:
    - pip

about:
  summary: 'ChainConsumer: Consumer your MCMC chains'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - craddis1
